// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNCOQeuVZ1aE-nMIvr5HHuvxW_5MLr_EU',
    appId: '1:707934860412:web:dc3460358eb5c86f7f45f9',
    messagingSenderId: '707934860412',
    projectId: 'flutter-with-firebase-b1aec',
    authDomain: 'flutter-with-firebase-b1aec.firebaseapp.com',
    storageBucket: 'flutter-with-firebase-b1aec.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzG4GK_dxuWVyHiKBviuOwlQcCsVEJcIo',
    appId: '1:707934860412:android:e13b5350441b73a87f45f9',
    messagingSenderId: '707934860412',
    projectId: 'flutter-with-firebase-b1aec',
    storageBucket: 'flutter-with-firebase-b1aec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5MLUpY0k-KH_FCax9DewuYV5WlTnHTsc',
    appId: '1:707934860412:ios:fd1168966f78f1e77f45f9',
    messagingSenderId: '707934860412',
    projectId: 'flutter-with-firebase-b1aec',
    storageBucket: 'flutter-with-firebase-b1aec.firebasestorage.app',
    iosClientId: '707934860412-7f6m63p2p9ks8vb6kiqcmr619q82kq5j.apps.googleusercontent.com',
    iosBundleId: 'com.example.brewCrew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5MLUpY0k-KH_FCax9DewuYV5WlTnHTsc',
    appId: '1:707934860412:ios:fd1168966f78f1e77f45f9',
    messagingSenderId: '707934860412',
    projectId: 'flutter-with-firebase-b1aec',
    storageBucket: 'flutter-with-firebase-b1aec.firebasestorage.app',
    iosClientId: '707934860412-7f6m63p2p9ks8vb6kiqcmr619q82kq5j.apps.googleusercontent.com',
    iosBundleId: 'com.example.brewCrew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNCOQeuVZ1aE-nMIvr5HHuvxW_5MLr_EU',
    appId: '1:707934860412:web:a958e48832a936b97f45f9',
    messagingSenderId: '707934860412',
    projectId: 'flutter-with-firebase-b1aec',
    authDomain: 'flutter-with-firebase-b1aec.firebaseapp.com',
    storageBucket: 'flutter-with-firebase-b1aec.firebasestorage.app',
  );
}
